version: "3.7"
services:
  caddy:
    build: 
      context: ../../app
    expose:
      - 3000
    networks:
      - proxy
    restart: unless-stopped
    labels:
      caddy: ${CLIENT_URL}
      caddy.reverse_proxy: "{{upstreams 3000}}"
    environment:
      - PUBLIC_ENDPOINT=${METEOR_WEBSOCKET_URL}

networks:
  proxy:
    external: true
