version: "3.7"
services:
  meteor:
    build: 
      context: ../../meteor
    expose:
      - 3000
    networks:
      - proxy
      - default
    restart: unless-stopped
    labels:
      caddy: ${METEOR_URL}
      caddy.reverse_proxy: "{{upstreams 3000}}"
    environment:
      PORT: 3000
      ROOT_URL: ${METEOR_URL}
      MONGO_URL: mongodb://mongo:27017/meteor
  mongo:
    image: bitnami/mongodb:5.0
    restart: always
    volumes:
      - db-data:/bitnami/mongodb
    networks:
      - default
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: meteor
      MONGODB_ADVERTISED_HOSTNAME: mongo
      ALLOW_EMPTY_PASSWORD: "yes"

networks:
  proxy:
    external: true

volumes:
  db-data:
