name: Deploy

on:
  workflow_run:
    workflows: [Build]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        script: |
          cd 360vr
          git pull
          cd deploy
          docker compose pull
          docker compose up -d